server:
  port: 8080
  servlet:
    context-path: /

############################# 数据库连接 #############################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clms_cps_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: Test@123
  redis:
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis:
  type-aliases-package: com.bc.domain
  #  debug 预编译参数详情
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

